# import nanoparticle and membranesimulation to construct demo simulation files (script and data) from templates

# maybe add PyLammps code that runs the demo without using the script, to show the alternative...